<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:38.
 */
class PDF2TextHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PDF2TextHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PDF2TextHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PDF2TextHelper::PrintOutput
     * @todo   Implement testPrintOutput().
     */
    public function testPrintOutput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PDF2TextHelper::decodePDF
     * @todo   Implement testDecodePDF().
     */
    public function testDecodePDF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PDF2TextHelper::decodeAsciiHex
     * @todo   Implement testDecodeAsciiHex().
     */
    public function testDecodeAsciiHex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PDF2TextHelper::decodeAscii85
     * @todo   Implement testDecodeAscii85().
     */
    public function testDecodeAscii85() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PDF2TextHelper::decodeFlate
     * @todo   Implement testDecodeFlate().
     */
    public function testDecodeFlate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PDF2TextHelper::getObjectOptions
     * @todo   Implement testGetObjectOptions().
     */
    public function testGetObjectOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PDF2TextHelper::getDecodedStream
     * @todo   Implement testGetDecodedStream().
     */
    public function testGetDecodedStream() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PDF2TextHelper::getDirtyTexts
     * @todo   Implement testGetDirtyTexts().
     */
    public function testGetDirtyTexts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PDF2TextHelper::getCharTransformations
     * @todo   Implement testGetCharTransformations().
     */
    public function testGetCharTransformations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PDF2TextHelper::getTextUsingTransformations
     * @todo   Implement testGetTextUsingTransformations().
     */
    public function testGetTextUsingTransformations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
