<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:02.
 */
class CpdfTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Cpdf
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Cpdf;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Cpdf::o_destination
     * @todo   Implement testO_destination().
     */
    public function testO_destination() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_viewerPreferences
     * @todo   Implement testO_viewerPreferences().
     */
    public function testO_viewerPreferences() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_catalog
     * @todo   Implement testO_catalog().
     */
    public function testO_catalog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_pages
     * @todo   Implement testO_pages().
     */
    public function testO_pages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_outlines
     * @todo   Implement testO_outlines().
     */
    public function testO_outlines() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_font
     * @todo   Implement testO_font().
     */
    public function testO_font() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_fontDescriptor
     * @todo   Implement testO_fontDescriptor().
     */
    public function testO_fontDescriptor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_fontEncoding
     * @todo   Implement testO_fontEncoding().
     */
    public function testO_fontEncoding() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_procset
     * @todo   Implement testO_procset().
     */
    public function testO_procset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_info
     * @todo   Implement testO_info().
     */
    public function testO_info() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_action
     * @todo   Implement testO_action().
     */
    public function testO_action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_annotation
     * @todo   Implement testO_annotation().
     */
    public function testO_annotation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_page
     * @todo   Implement testO_page().
     */
    public function testO_page() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_contents
     * @todo   Implement testO_contents().
     */
    public function testO_contents() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_image
     * @todo   Implement testO_image().
     */
    public function testO_image() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_extGState
     * @todo   Implement testO_extGState().
     */
    public function testO_extGState() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::o_encryption
     * @todo   Implement testO_encryption().
     */
    public function testO_encryption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::md5_16
     * @todo   Implement testMd5_16().
     */
    public function testMd5_16() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::encryptInit
     * @todo   Implement testEncryptInit().
     */
    public function testEncryptInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::ARC4_init
     * @todo   Implement testARC4_init().
     */
    public function testARC4_init() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::ARC4
     * @todo   Implement testARC4().
     */
    public function testARC4() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addLink
     * @todo   Implement testAddLink().
     */
    public function testAddLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addInternalLink
     * @todo   Implement testAddInternalLink().
     */
    public function testAddInternalLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::setEncryption
     * @todo   Implement testSetEncryption().
     */
    public function testSetEncryption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::checkAllHere
     * @todo   Implement testCheckAllHere().
     */
    public function testCheckAllHere() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::output
     * @todo   Implement testOutput().
     */
    public function testOutput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::newDocument
     * @todo   Implement testNewDocument().
     */
    public function testNewDocument() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::openFont
     * @todo   Implement testOpenFont().
     */
    public function testOpenFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::selectFont
     * @todo   Implement testSelectFont().
     */
    public function testSelectFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::setCurrentFont
     * @todo   Implement testSetCurrentFont().
     */
    public function testSetCurrentFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::getFirstPageId
     * @todo   Implement testGetFirstPageId().
     */
    public function testGetFirstPageId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addContent
     * @todo   Implement testAddContent().
     */
    public function testAddContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::setColor
     * @todo   Implement testSetColor().
     */
    public function testSetColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::setStrokeColor
     * @todo   Implement testSetStrokeColor().
     */
    public function testSetStrokeColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::setGraphicsState
     * @todo   Implement testSetGraphicsState().
     */
    public function testSetGraphicsState() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::setLineTransparency
     * @todo   Implement testSetLineTransparency().
     */
    public function testSetLineTransparency() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::setFillTransparency
     * @todo   Implement testSetFillTransparency().
     */
    public function testSetFillTransparency() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::line
     * @todo   Implement testLine().
     */
    public function testLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::curve
     * @todo   Implement testCurve().
     */
    public function testCurve() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::partEllipse
     * @todo   Implement testPartEllipse().
     */
    public function testPartEllipse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::filledEllipse
     * @todo   Implement testFilledEllipse().
     */
    public function testFilledEllipse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::ellipse
     * @todo   Implement testEllipse().
     */
    public function testEllipse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::setLineStyle
     * @todo   Implement testSetLineStyle().
     */
    public function testSetLineStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::polygon
     * @todo   Implement testPolygon().
     */
    public function testPolygon() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::filledRectangle
     * @todo   Implement testFilledRectangle().
     */
    public function testFilledRectangle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::rectangle
     * @todo   Implement testRectangle().
     */
    public function testRectangle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::newPage
     * @todo   Implement testNewPage().
     */
    public function testNewPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::stream
     * @todo   Implement testStream().
     */
    public function testStream() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::getFontHeight
     * @todo   Implement testGetFontHeight().
     */
    public function testGetFontHeight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::getFontDecender
     * @todo   Implement testGetFontDecender().
     */
    public function testGetFontDecender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::filterText
     * @todo   Implement testFilterText().
     */
    public function testFilterText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::PRVTgetTextPosition
     * @todo   Implement testPRVTgetTextPosition().
     */
    public function testPRVTgetTextPosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::PRVTcheckTextDirective
     * @todo   Implement testPRVTcheckTextDirective().
     */
    public function testPRVTcheckTextDirective() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::PRVTcheckTextDirective1
     * @todo   Implement testPRVTcheckTextDirective1().
     */
    public function testPRVTcheckTextDirective1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addText
     * @todo   Implement testAddText().
     */
    public function testAddText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::getTextWidth
     * @todo   Implement testGetTextWidth().
     */
    public function testGetTextWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::PRVTadjustWrapText
     * @todo   Implement testPRVTadjustWrapText().
     */
    public function testPRVTadjustWrapText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addTextWrap
     * @todo   Implement testAddTextWrap().
     */
    public function testAddTextWrap() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::saveState
     * @todo   Implement testSaveState().
     */
    public function testSaveState() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::restoreState
     * @todo   Implement testRestoreState().
     */
    public function testRestoreState() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::openObject
     * @todo   Implement testOpenObject().
     */
    public function testOpenObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::reopenObject
     * @todo   Implement testReopenObject().
     */
    public function testReopenObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::closeObject
     * @todo   Implement testCloseObject().
     */
    public function testCloseObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::stopObject
     * @todo   Implement testStopObject().
     */
    public function testStopObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addObject
     * @todo   Implement testAddObject().
     */
    public function testAddObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::serializeObject
     * @todo   Implement testSerializeObject().
     */
    public function testSerializeObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::restoreSerializedObject
     * @todo   Implement testRestoreSerializedObject().
     */
    public function testRestoreSerializedObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addInfo
     * @todo   Implement testAddInfo().
     */
    public function testAddInfo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::setPreferences
     * @todo   Implement testSetPreferences().
     */
    public function testSetPreferences() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::PRVT_getBytes
     * @todo   Implement testPRVT_getBytes().
     */
    public function testPRVT_getBytes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addPngFromFile
     * @todo   Implement testAddPngFromFile().
     */
    public function testAddPngFromFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addJpegFromFile
     * @todo   Implement testAddJpegFromFile().
     */
    public function testAddJpegFromFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addImage
     * @todo   Implement testAddImage().
     */
    public function testAddImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addJpegImage_common
     * @todo   Implement testAddJpegImage_common().
     */
    public function testAddJpegImage_common() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::openHere
     * @todo   Implement testOpenHere().
     */
    public function testOpenHere() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addDestination
     * @todo   Implement testAddDestination().
     */
    public function testAddDestination() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::setFontFamily
     * @todo   Implement testSetFontFamily().
     */
    public function testSetFontFamily() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::addMessage
     * @todo   Implement testAddMessage().
     */
    public function testAddMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cpdf::transaction
     * @todo   Implement testTransaction().
     */
    public function testTransaction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
