<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:13.
 */
class CellmapTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Cellmap
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Cellmap;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Cellmap::reset
     * @todo   Implement testReset().
     */
    public function testReset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_num_rows
     * @todo   Implement testGet_num_rows().
     */
    public function testGet_num_rows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_num_cols
     * @todo   Implement testGet_num_cols().
     */
    public function testGet_num_cols() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_columns
     * @todo   Implement testGet_columns().
     */
    public function testGet_columns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_column
     * @todo   Implement testGet_column().
     */
    public function testGet_column() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_rows
     * @todo   Implement testGet_rows().
     */
    public function testGet_rows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_row
     * @todo   Implement testGet_row().
     */
    public function testGet_row() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_border
     * @todo   Implement testGet_border().
     */
    public function testGet_border() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_border_properties
     * @todo   Implement testGet_border_properties().
     */
    public function testGet_border_properties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_spanned_cells
     * @todo   Implement testGet_spanned_cells().
     */
    public function testGet_spanned_cells() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_frame_position
     * @todo   Implement testGet_frame_position().
     */
    public function testGet_frame_position() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_frame_width
     * @todo   Implement testGet_frame_width().
     */
    public function testGet_frame_width() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::get_frame_height
     * @todo   Implement testGet_frame_height().
     */
    public function testGet_frame_height() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::set_column_width
     * @todo   Implement testSet_column_width().
     */
    public function testSet_column_width() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::set_row_height
     * @todo   Implement testSet_row_height().
     */
    public function testSet_row_height() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::add_frame
     * @todo   Implement testAdd_frame().
     */
    public function testAdd_frame() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::add_row
     * @todo   Implement testAdd_row().
     */
    public function testAdd_row() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::remove_row
     * @todo   Implement testRemove_row().
     */
    public function testRemove_row() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::remove_row_group
     * @todo   Implement testRemove_row_group().
     */
    public function testRemove_row_group() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::update_row_group
     * @todo   Implement testUpdate_row_group().
     */
    public function testUpdate_row_group() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::assign_x_positions
     * @todo   Implement testAssign_x_positions().
     */
    public function testAssign_x_positions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::assign_frame_heights
     * @todo   Implement testAssign_frame_heights().
     */
    public function testAssign_frame_heights() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::set_frame_heights
     * @todo   Implement testSet_frame_heights().
     */
    public function testSet_frame_heights() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cellmap::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
