<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:08.
 */
class DOMPDFTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DOMPDF
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DOMPDF;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DOMPDF::get_tree
     * @todo   Implement testGet_tree().
     */
    public function testGet_tree() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::set_protocol
     * @todo   Implement testSet_protocol().
     */
    public function testSet_protocol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::set_host
     * @todo   Implement testSet_host().
     */
    public function testSet_host() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::set_base_path
     * @todo   Implement testSet_base_path().
     */
    public function testSet_base_path() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::get_protocol
     * @todo   Implement testGet_protocol().
     */
    public function testGet_protocol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::get_host
     * @todo   Implement testGet_host().
     */
    public function testGet_host() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::get_base_path
     * @todo   Implement testGet_base_path().
     */
    public function testGet_base_path() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::get_canvas
     * @todo   Implement testGet_canvas().
     */
    public function testGet_canvas() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::load_html_file
     * @todo   Implement testLoad_html_file().
     */
    public function testLoad_html_file() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::load_html
     * @todo   Implement testLoad_html().
     */
    public function testLoad_html() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::set_paper
     * @todo   Implement testSet_paper().
     */
    public function testSet_paper() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::enable_caching
     * @todo   Implement testEnable_caching().
     */
    public function testEnable_caching() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::render
     * @todo   Implement testRender().
     */
    public function testRender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::stream
     * @todo   Implement testStream().
     */
    public function testStream() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DOMPDF::output
     * @todo   Implement testOutput().
     */
    public function testOutput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
