<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:08.
 */
class Frame_TreeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Frame_Tree
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Frame_Tree;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Frame_Tree::get_dom
     * @todo   Implement testGet_dom().
     */
    public function testGet_dom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Frame_Tree::get_root
     * @todo   Implement testGet_root().
     */
    public function testGet_root() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Frame_Tree::get_frame
     * @todo   Implement testGet_frame().
     */
    public function testGet_frame() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Frame_Tree::get_frames
     * @todo   Implement testGet_frames().
     */
    public function testGet_frames() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Frame_Tree::build_tree
     * @todo   Implement testBuild_tree().
     */
    public function testBuild_tree() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
