<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:35.
 */
class Frame_ReflowerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Frame_Reflower
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Frame_Reflower;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Frame_Reflower::dispose
     * @todo   Implement testDispose().
     */
    public function testDispose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Frame_Reflower::get_min_max_width
     * @todo   Implement testGet_min_max_width().
     */
    public function testGet_min_max_width() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
