<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:06.
 */
class Frame_FactoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Frame_Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Frame_Factory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Frame_Factory::decorate_root
     * @todo   Implement testDecorate_root().
     */
    public function testDecorate_root() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Frame_Factory::decorate_frame
     * @todo   Implement testDecorate_frame().
     */
    public function testDecorate_frame() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
