<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:12.
 */
class PHP_EvaluatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHP_Evaluator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHP_Evaluator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PHP_Evaluator::evaluate
     * @todo   Implement testEvaluate().
     */
    public function testEvaluate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Evaluator::render
     * @todo   Implement testRender().
     */
    public function testRender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
