<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:34.
 */
class StylesheetTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Stylesheet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Stylesheet;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Stylesheet::set_protocol
     * @todo   Implement testSet_protocol().
     */
    public function testSet_protocol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::set_host
     * @todo   Implement testSet_host().
     */
    public function testSet_host() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::set_base_path
     * @todo   Implement testSet_base_path().
     */
    public function testSet_base_path() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::get_protocol
     * @todo   Implement testGet_protocol().
     */
    public function testGet_protocol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::get_host
     * @todo   Implement testGet_host().
     */
    public function testGet_host() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::get_base_path
     * @todo   Implement testGet_base_path().
     */
    public function testGet_base_path() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::add_style
     * @todo   Implement testAdd_style().
     */
    public function testAdd_style() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::lookup
     * @todo   Implement testLookup().
     */
    public function testLookup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::create_style
     * @todo   Implement testCreate_style().
     */
    public function testCreate_style() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::load_css
     * @todo   Implement testLoad_css().
     */
    public function testLoad_css() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::load_css_file
     * @todo   Implement testLoad_css_file().
     */
    public function testLoad_css_file() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::apply_styles
     * @todo   Implement testApply_styles().
     */
    public function testApply_styles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Stylesheet::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
