<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:15.
 */
class StyleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Style
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Style;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Style::dispose
     * @todo   Implement testDispose().
     */
    public function testDispose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_stylesheet
     * @todo   Implement testGet_stylesheet().
     */
    public function testGet_stylesheet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::length_in_pt
     * @todo   Implement testLength_in_pt().
     */
    public function testLength_in_pt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::inherit
     * @todo   Implement testInherit().
     */
    public function testInherit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::merge
     * @todo   Implement testMerge().
     */
    public function testMerge() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::munge_colour
     * @todo   Implement testMunge_colour().
     */
    public function testMunge_colour() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::munge_color
     * @todo   Implement testMunge_color().
     */
    public function testMunge_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::__set
     * @todo   Implement test__set().
     */
    public function test__set() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::__get
     * @todo   Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_font_family
     * @todo   Implement testGet_font_family().
     */
    public function testGet_font_family() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_font_size
     * @todo   Implement testGet_font_size().
     */
    public function testGet_font_size() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_word_spacing
     * @todo   Implement testGet_word_spacing().
     */
    public function testGet_word_spacing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_line_height
     * @todo   Implement testGet_line_height().
     */
    public function testGet_line_height() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_color
     * @todo   Implement testGet_color().
     */
    public function testGet_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_background_color
     * @todo   Implement testGet_background_color().
     */
    public function testGet_background_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_background_position
     * @todo   Implement testGet_background_position().
     */
    public function testGet_background_position() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_top_color
     * @todo   Implement testGet_border_top_color().
     */
    public function testGet_border_top_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_right_color
     * @todo   Implement testGet_border_right_color().
     */
    public function testGet_border_right_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_bottom_color
     * @todo   Implement testGet_border_bottom_color().
     */
    public function testGet_border_bottom_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_left_color
     * @todo   Implement testGet_border_left_color().
     */
    public function testGet_border_left_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_top_width
     * @todo   Implement testGet_border_top_width().
     */
    public function testGet_border_top_width() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_right_width
     * @todo   Implement testGet_border_right_width().
     */
    public function testGet_border_right_width() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_bottom_width
     * @todo   Implement testGet_border_bottom_width().
     */
    public function testGet_border_bottom_width() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_left_width
     * @todo   Implement testGet_border_left_width().
     */
    public function testGet_border_left_width() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_properties
     * @todo   Implement testGet_border_properties().
     */
    public function testGet_border_properties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_top
     * @todo   Implement testGet_border_top().
     */
    public function testGet_border_top() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_right
     * @todo   Implement testGet_border_right().
     */
    public function testGet_border_right() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_bottom
     * @todo   Implement testGet_border_bottom().
     */
    public function testGet_border_bottom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_left
     * @todo   Implement testGet_border_left().
     */
    public function testGet_border_left() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::get_border_spacing
     * @todo   Implement testGet_border_spacing().
     */
    public function testGet_border_spacing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_color
     * @todo   Implement testSet_color().
     */
    public function testSet_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_background_color
     * @todo   Implement testSet_background_color().
     */
    public function testSet_background_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_background_image
     * @todo   Implement testSet_background_image().
     */
    public function testSet_background_image() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_font_size
     * @todo   Implement testSet_font_size().
     */
    public function testSet_font_size() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_page_break_before
     * @todo   Implement testSet_page_break_before().
     */
    public function testSet_page_break_before() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_page_break_after
     * @todo   Implement testSet_page_break_after().
     */
    public function testSet_page_break_after() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_margin_top
     * @todo   Implement testSet_margin_top().
     */
    public function testSet_margin_top() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_margin_right
     * @todo   Implement testSet_margin_right().
     */
    public function testSet_margin_right() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_margin_bottom
     * @todo   Implement testSet_margin_bottom().
     */
    public function testSet_margin_bottom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_margin_left
     * @todo   Implement testSet_margin_left().
     */
    public function testSet_margin_left() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_margin
     * @todo   Implement testSet_margin().
     */
    public function testSet_margin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_padding_top
     * @todo   Implement testSet_padding_top().
     */
    public function testSet_padding_top() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_padding_right
     * @todo   Implement testSet_padding_right().
     */
    public function testSet_padding_right() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_padding_bottom
     * @todo   Implement testSet_padding_bottom().
     */
    public function testSet_padding_bottom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_padding_left
     * @todo   Implement testSet_padding_left().
     */
    public function testSet_padding_left() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_padding
     * @todo   Implement testSet_padding().
     */
    public function testSet_padding() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_border_top
     * @todo   Implement testSet_border_top().
     */
    public function testSet_border_top() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_border_right
     * @todo   Implement testSet_border_right().
     */
    public function testSet_border_right() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_border_bottom
     * @todo   Implement testSet_border_bottom().
     */
    public function testSet_border_bottom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_border_left
     * @todo   Implement testSet_border_left().
     */
    public function testSet_border_left() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_border
     * @todo   Implement testSet_border().
     */
    public function testSet_border() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_border_width
     * @todo   Implement testSet_border_width().
     */
    public function testSet_border_width() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_border_color
     * @todo   Implement testSet_border_color().
     */
    public function testSet_border_color() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_border_style
     * @todo   Implement testSet_border_style().
     */
    public function testSet_border_style() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_border_spacing
     * @todo   Implement testSet_border_spacing().
     */
    public function testSet_border_spacing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_list_style_image
     * @todo   Implement testSet_list_style_image().
     */
    public function testSet_list_style_image() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::set_list_style
     * @todo   Implement testSet_list_style().
     */
    public function testSet_list_style() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Style::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
